// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package xbasm

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3f8d0da3DecodeGithubComBlockyBasmGoSdkXXbasm(in *jlexer.Lexer, out *sliceOfSliceOfBytes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(sliceOfSliceOfBytes, 0, 2)
			} else {
				*out = sliceOfSliceOfBytes{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 []uint8
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				v1 = in.Bytes()
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3f8d0da3EncodeGithubComBlockyBasmGoSdkXXbasm(out *jwriter.Writer, in sliceOfSliceOfBytes) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v3, v4 := range in {
			if v3 > 0 {
				out.RawByte(',')
			}
			out.Base64Bytes(v4)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v sliceOfSliceOfBytes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3f8d0da3EncodeGithubComBlockyBasmGoSdkXXbasm(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sliceOfSliceOfBytes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3f8d0da3EncodeGithubComBlockyBasmGoSdkXXbasm(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sliceOfSliceOfBytes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3f8d0da3DecodeGithubComBlockyBasmGoSdkXXbasm(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sliceOfSliceOfBytes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3f8d0da3DecodeGithubComBlockyBasmGoSdkXXbasm(l, v)
}
