// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package basm

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGoBkyShPortal(in *jlexer.Lexer, out *VerifyAttestationResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ok":
			out.IsOk = bool(in.Bool())
		case "value":
			(out.Value).UnmarshalEasyJSON(in)
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGoBkyShPortal(out *jwriter.Writer, in VerifyAttestationResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ok\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsOk))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		(in.Value).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VerifyAttestationResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGoBkyShPortal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VerifyAttestationResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGoBkyShPortal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VerifyAttestationResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGoBkyShPortal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VerifyAttestationResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGoBkyShPortal(l, v)
}
func easyjson56de76c1DecodeGoBkyShPortal1(in *jlexer.Lexer, out *VerifyAttestationOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "raw_claims":
			if in.IsNull() {
				in.Skip()
				out.RawClaims = nil
			} else {
				out.RawClaims = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGoBkyShPortal1(out *jwriter.Writer, in VerifyAttestationOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"raw_claims\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.RawClaims)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VerifyAttestationOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGoBkyShPortal1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VerifyAttestationOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGoBkyShPortal1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VerifyAttestationOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGoBkyShPortal1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VerifyAttestationOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGoBkyShPortal1(l, v)
}
func easyjson56de76c1DecodeGoBkyShPortal2(in *jlexer.Lexer, out *VerifyAttestationInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "enclave_attested_app_public_key":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.EnclaveAttestedKey).UnmarshalJSON(data))
			}
		case "transitive_attestation":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TransitiveAttestation).UnmarshalJSON(data))
			}
		case "acceptable_measurements":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.AcceptableMeasures).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGoBkyShPortal2(out *jwriter.Writer, in VerifyAttestationInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"enclave_attested_app_public_key\":"
		out.RawString(prefix[1:])
		out.Raw((in.EnclaveAttestedKey).MarshalJSON())
	}
	{
		const prefix string = ",\"transitive_attestation\":"
		out.RawString(prefix)
		out.Raw((in.TransitiveAttestation).MarshalJSON())
	}
	{
		const prefix string = ",\"acceptable_measurements\":"
		out.RawString(prefix)
		out.Raw((in.AcceptableMeasures).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VerifyAttestationInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGoBkyShPortal2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VerifyAttestationInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGoBkyShPortal2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VerifyAttestationInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGoBkyShPortal2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VerifyAttestationInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGoBkyShPortal2(l, v)
}
func easyjson56de76c1DecodeGoBkyShPortal3(in *jlexer.Lexer, out *HTTPRequestResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ok":
			out.IsOk = bool(in.Bool())
		case "value":
			(out.Value).UnmarshalEasyJSON(in)
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGoBkyShPortal3(out *jwriter.Writer, in HTTPRequestResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ok\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsOk))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		(in.Value).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HTTPRequestResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGoBkyShPortal3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HTTPRequestResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGoBkyShPortal3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HTTPRequestResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGoBkyShPortal3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HTTPRequestResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGoBkyShPortal3(l, v)
}
func easyjson56de76c1DecodeGoBkyShPortal4(in *jlexer.Lexer, out *HTTPRequestOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status_code":
			out.StatusCode = int(in.Int())
		case "body":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				out.Body = in.Bytes()
			}
		case "headers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Headers = make(map[string][]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 []string
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						in.Delim('[')
						if v5 == nil {
							if !in.IsDelim(']') {
								v5 = make([]string, 0, 4)
							} else {
								v5 = []string{}
							}
						} else {
							v5 = (v5)[:0]
						}
						for !in.IsDelim(']') {
							var v6 string
							v6 = string(in.String())
							v5 = append(v5, v6)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Headers)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGoBkyShPortal4(out *jwriter.Writer, in HTTPRequestOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status_code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.StatusCode))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Body)
	}
	{
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		if in.Headers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.Headers {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				if v9Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v10, v11 := range v9Value {
						if v10 > 0 {
							out.RawByte(',')
						}
						out.String(string(v11))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HTTPRequestOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGoBkyShPortal4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HTTPRequestOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGoBkyShPortal4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HTTPRequestOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGoBkyShPortal4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HTTPRequestOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGoBkyShPortal4(l, v)
}
func easyjson56de76c1DecodeGoBkyShPortal5(in *jlexer.Lexer, out *HTTPRequestInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "method":
			out.Method = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "headers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Headers = make(map[string][]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v12 []string
					if in.IsNull() {
						in.Skip()
						v12 = nil
					} else {
						in.Delim('[')
						if v12 == nil {
							if !in.IsDelim(']') {
								v12 = make([]string, 0, 4)
							} else {
								v12 = []string{}
							}
						} else {
							v12 = (v12)[:0]
						}
						for !in.IsDelim(']') {
							var v13 string
							v13 = string(in.String())
							v12 = append(v12, v13)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Headers)[key] = v12
					in.WantComma()
				}
				in.Delim('}')
			}
		case "body":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				out.Body = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGoBkyShPortal5(out *jwriter.Writer, in HTTPRequestInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		if in.Headers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.Headers {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				if v15Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v16, v17 := range v15Value {
						if v16 > 0 {
							out.RawByte(',')
						}
						out.String(string(v17))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Body)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HTTPRequestInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGoBkyShPortal5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HTTPRequestInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGoBkyShPortal5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HTTPRequestInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGoBkyShPortal5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HTTPRequestInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGoBkyShPortal5(l, v)
}
