// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package basm

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm(in *jlexer.Lexer, out *verifyAttestationOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "raw_claims":
			if in.IsNull() {
				in.Skip()
				out.RawClaims = nil
			} else {
				out.RawClaims = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm(out *jwriter.Writer, in verifyAttestationOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"raw_claims\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.RawClaims)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v verifyAttestationOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *verifyAttestationOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm(l, v)
}
func easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm1(in *jlexer.Lexer, out *verifyAttestationInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "enclave_attested_app_public_key":
			out.EnclaveAttestedKey = string(in.String())
		case "transitive_attestation":
			out.TransitiveAttestation = string(in.String())
		case "acceptable_measurements":
			if in.IsNull() {
				in.Skip()
				out.AcceptableMeasures = nil
			} else {
				in.Delim('[')
				if out.AcceptableMeasures == nil {
					if !in.IsDelim(']') {
						out.AcceptableMeasures = make([]EnclaveMeasurement, 0, 2)
					} else {
						out.AcceptableMeasures = []EnclaveMeasurement{}
					}
				} else {
					out.AcceptableMeasures = (out.AcceptableMeasures)[:0]
				}
				for !in.IsDelim(']') {
					var v4 EnclaveMeasurement
					easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm2(in, &v4)
					out.AcceptableMeasures = append(out.AcceptableMeasures, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm1(out *jwriter.Writer, in verifyAttestationInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"enclave_attested_app_public_key\":"
		out.RawString(prefix[1:])
		out.String(string(in.EnclaveAttestedKey))
	}
	{
		const prefix string = ",\"transitive_attestation\":"
		out.RawString(prefix)
		out.String(string(in.TransitiveAttestation))
	}
	{
		const prefix string = ",\"acceptable_measurements\":"
		out.RawString(prefix)
		if in.AcceptableMeasures == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.AcceptableMeasures {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm2(out, v6)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v verifyAttestationInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *verifyAttestationInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm1(l, v)
}
func easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm2(in *jlexer.Lexer, out *EnclaveMeasurement) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Platform":
			out.Platform = string(in.String())
		case "Code":
			out.Code = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm2(out *jwriter.Writer, in EnclaveMeasurement) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Platform\":"
		out.RawString(prefix[1:])
		out.String(string(in.Platform))
	}
	{
		const prefix string = ",\"Code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	out.RawByte('}')
}
func easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm3(in *jlexer.Lexer, out *result) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ok":
			out.IsOK = bool(in.Bool())
		case "error":
			out.Error = string(in.String())
		case "value":
			if in.IsNull() {
				in.Skip()
				out.Value = nil
			} else {
				out.Value = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm3(out *jwriter.Writer, in result) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ok\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsOK))
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Value)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v result) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm3(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *result) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm3(l, v)
}
func easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm4(in *jlexer.Lexer, out *httpRequestOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status_code":
			out.StatusCode = int(in.Int())
		case "body":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				out.Body = in.Bytes()
			}
		case "headers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Headers = make(map[string][]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 []string
					if in.IsNull() {
						in.Skip()
						v11 = nil
					} else {
						in.Delim('[')
						if v11 == nil {
							if !in.IsDelim(']') {
								v11 = make([]string, 0, 4)
							} else {
								v11 = []string{}
							}
						} else {
							v11 = (v11)[:0]
						}
						for !in.IsDelim(']') {
							var v12 string
							v12 = string(in.String())
							v11 = append(v11, v12)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Headers)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm4(out *jwriter.Writer, in httpRequestOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status_code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.StatusCode))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Body)
	}
	{
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		if in.Headers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.Headers {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				if v15Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v16, v17 := range v15Value {
						if v16 > 0 {
							out.RawByte(',')
						}
						out.String(string(v17))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v httpRequestOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm4(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *httpRequestOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm4(l, v)
}
func easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm5(in *jlexer.Lexer, out *httpRequestInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "method":
			out.Method = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "headers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Headers = make(map[string][]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v18 []string
					if in.IsNull() {
						in.Skip()
						v18 = nil
					} else {
						in.Delim('[')
						if v18 == nil {
							if !in.IsDelim(']') {
								v18 = make([]string, 0, 4)
							} else {
								v18 = []string{}
							}
						} else {
							v18 = (v18)[:0]
						}
						for !in.IsDelim(']') {
							var v19 string
							v19 = string(in.String())
							v18 = append(v18, v19)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Headers)[key] = v18
					in.WantComma()
				}
				in.Delim('}')
			}
		case "body":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				out.Body = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm5(out *jwriter.Writer, in httpRequestInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		if in.Headers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v21First := true
			for v21Name, v21Value := range in.Headers {
				if v21First {
					v21First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v21Name))
				out.RawByte(':')
				if v21Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v22, v23 := range v21Value {
						if v22 > 0 {
							out.RawByte(',')
						}
						out.String(string(v23))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Body)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v httpRequestInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComBlockyBasmGoSdkBasm5(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *httpRequestInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComBlockyBasmGoSdkBasm5(l, v)
}
