name: Notify Slack

on:
  push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Post a message in a channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.NOTIFY_SLACK_MONITORING_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          blocks:
          - type: section
          text:
          type: mrkdwn
          text: ":x: *GitHub Action `${{ github.workflow }}` failed!*"
          - type: section
          fields:
          - type: mrkdwn
           text: "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
          - type: mrkdwn
           text: "*Ref:*\n`${{ github.ref }}`"
          - type: mrkdwn
           text: "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}"
          - type: mrkdwn
           text: "*Author:*\n<https://github.com/${{ github.actor }}|${{ github.actor }}>"
          - type: mrkdwn
           text: "*Workflow:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
          - type: context
          elements:
          - type: mrkdwn
           text: "Event: `${{ github.event_name }}` • Job status: `${{ job.status }}`"
