name: Notify Slack

on:
  push

jobs:
  notify:
    uses: blocky/actions/.github/workflows/notify-failure.yml@main
    secrets:
      slack-webhook: ${{ secrets.NOTIFY_SLACK_TMP_NOTIFY_SLACK_TEST_WEBHOOK_URL }}
