name: Notify Slack

on:
  push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: Post a message in a channel
#      uses: slackapi/slack-github-action@v2.0.0
#      with:
#        webhook: ${{ secrets.NOTIFY_SLACK_MONITORING_WEBHOOK_URL }}
#        webhook-type: incoming-webhook
#        payload: |
#          text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#          blocks:
#            - type: "section"
#              text:
#                type: "mrkdwn"
#                text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#          attachments:
#            color: "#f2c744"
#            blocks:
#              - type: "section"
#                text:
#                  type: "plain_text"
#                  text: "This is a plain text section block."
#

    - name: "integration(incoming): post a message via payload file"
      id: payload_file
      uses: slackapi/slack-github-action@v2.0.0
      with:
        errors: true
        payload-file-path: ./.github/workflows/resources/incoming-webhook.json
        payload-templated: true
        webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
        webhook-type: incoming-webhook
      env:
        JOB_STATUS: ${{ job.status }}
        ATTACHMENT_COLOR: ${{ (job.status == 'success' && 'good') || (job.status == 'failure' && 'danger') || 'warning' }}
