name: Scheduled Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Run tests
        run: nix-shell --pure --run "make test"
